{% set version = "2.56.4" %}
{% set major_minor = ".".join(version.split(".")[:2]) %}
{% set abi_version = "1.0" %}

package:
  name: atk
  version: {{ version }}

source:
  url: https://gitlab.gnome.org/GNOME/at-spi2-core/-/archive/{{ version }}/at-spi2-core-{{ version }}.tar.gz
  sha256: 0642c872ab8820acd0e56f2a08645597cd8c09718e94c090ceded76730d6a76a

build:
  number: 0
  run_exports:
    - atk-{{ abi_version }} >={{ version }}

outputs:
  - name: atk-{{ abi_version }}
    script: build_atk.sh  # [unix]
    script: bld_atk.bat  # [win]
    build:
      run_exports:
        - atk-{{ abi_version }} >={{ version }}
    requirements:
      build:
        - {{ stdlib('c') }}
        - {{ compiler('c') }}
        # Required for the conda-forge meson cross-compilation config to work
        - {{ compiler('cxx') }}
        - cmake
        - meson
        - gobject-introspection 1.*
        - ninja
        - python *
        - pkg-config
        - glib  # [build_platform != target_platform]
      host:
        - dbus
        - glib
        - libintl-devel  # [not linux]
        - libxml2-devel
        - zlib
      run:
        - libglib
      run_constrained:
        - atk-{{ abi_version }} {{ version }}

    test:
      requires:
        - pkg-config
      commands:
        # verify that libs get installed and can be located through pkg-config
        {% set lib = "atk-" + abi_version  %}
        - test -f $PREFIX/lib/lib{{ lib }}${SHLIB_EXT}  # [unix]
        - test -f `pkg-config --variable=libdir --dont-define-prefix atk`/lib{{ lib }}${SHLIB_EXT}  # [unix]
        - if not exist %PREFIX%\\Library\\bin\\{{ lib }}-0.dll exit 1  # [win]
        - for /f "usebackq tokens=*" %%a in (`pkg-config --variable=exec_prefix --dont-define-prefix atk`) do if not exist "%%a/bin/{{ lib }}-0.dll" exit 1  # [win]
        - if not exist %PREFIX%\\Library\\lib\\{{ lib }}.lib exit 1  # [win]
        - for /f "usebackq tokens=*" %%a in (`pkg-config --variable=libdir --dont-define-prefix atk`) do if not exist "%%a/{{ lib }}.lib" exit 1  # [win]

  - name: atk
    requirements:
      run:
        - atk-{{ abi_version }} {{ version }}
    test:
      commands:
        - test -f $PREFIX/lib/libatk-{{ abi_version }}${SHLIB_EXT}  # [unix]

about:
  home: http://www.gtk.org/
  license: LGPL-2.0-or-later
  license_file: COPYING
  summary: Accessibility Toolkit.
  dev_url: https://gitlab.gnome.org/GNOME/at-spi2-core

extra:
  recipe-maintainers:
    - pkgw
    - ocefpaf
    - isuruf
    - tschoonj
